version: '3.8'

name: glerk-docker

volumes:
  glerk_postgres:
    external: true

services:
  db:
    container_name: glerk_db
    image: postgres:15.4
    command: -p 5453
    env_file:
      - ./.env
    ports:
      - "5453:5453"
    volumes:
      - glerk_postgres:/var/lib/postgresql/data/
  web:
    container_name: glerk_web
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=db
      - STATIC_ROOT=/code/app/static/
      - MEDIA_ROOT=/code/app/media/
    command:
      - '/code/bin/wait-for-it.sh'
      - 'db:5453'
      - '--'
      - 'python'
      - '/code/app/manage.py'
      - 'runserver'
      - '0.0.0.0:5353'
    volumes:
      - .:/code
    ports:
      - "5353:5353"
    depends_on:
      - db
