# Generated by Django 5.0.2 on 2024-08-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='all_data',
            field=models.JSONField(null=True),
        ),
    ]
